[package]
name = "wai/wai-hashids"
version = "0.1.1"
description = "Hashids with WAI bindings"
repository = "https://github.com/wasmerio/wai-hashids"
readme = "README.md"

[[module]]
name = "hashids"
source = "target/wasm32-unknown-unknown/release/wai_hashids.wasm"

[module.bindings]
wai-version = "0.2.0"
exports = "./bindings.wai"

